behaviors:
  RobotBrain:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0002
      learning_rate_schedule: linear
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 80
    checkpoint_interval: 100000
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000

  HumanBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0001
      learning_rate_schedule: linear
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      hidden_units: 256
      num_layers: 3
      normalize: true
    reward_signals:
      extrinsic:
        gamma: 0.98
        strength: 1.0
    keep_checkpoints: 80
    checkpoint_interval: 100000
    max_steps: 5000000
    time_horizon: 48
    summary_freq: 10000